export const envKeys = {
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_DATABASE: 'DB_DATABASE',

  NODE_ENV: 'NODE_ENV',

  CLIENT_URLS: 'CLIENT_URLS',
  WEB_CLIENT_URL: 'WEB_CLIENT_URL',

  SERVER_API_URL: 'SERVER_API_URL',
  PORT: 'PORT',

  EMAIL_USER: 'EMAIL_USER',
  EMAIL_PASS: 'EMAIL_PASS',
  EMAIL_PORT: 'EMAIL_PORT',
  EMAIL_HOST: 'EMAIL_HOST',
  EMAIL_SENDER: 'EMAIL_SENDER',

  JWT_SECRET: 'JWT_SECRET',

  ENCRYPTION_KEY: 'ENCRYPTION_KEY',
  ENCRYPTION_IV: 'ENCRYPTION_IV',

  COOKIE_EXPIRE_TIME: 'COOKIE_EXPIRE_TIME',
  ACCESS_TOKEN_EXPIRATION: 'ACCESS_TOKEN_EXPIRATION',
  REFRESH_TOKEN_EXPIRATION: 'REFRESH_TOKEN_EXPIRATION',

  RATE_LIMIT: 'RATE_LIMIT',
  TIME_TO_LIVE: 'TIME_TO_LIVE',

  BASIC_AUTH_PASSWORD: 'BASIC_AUTH_PASSWORD',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
};
