name: Deploy to DigitalOcean

on:
  push:
    branches:
      - dev 
      - main
    types:
      - pushed
      - merged

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to DigitalOcean droplet via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/jerry-demo-1-be
            git pull origin dev
            sudo docker compose -f docker-compose.prod.yml up --build
