export enum StatusTwoFa {
  DISABLED = 'DISABLED',
  ENABLED = 'ENABLED',
  NOT_REGISTERED = 'NOT_REGISTERED',
}

export enum StatusEnableTwoFa {
  TWO_FA_ENABLED_NO_SECRET = 'TWO_FA_ENABLED_NO_SECRET',
  TWO_FA_ENABLED_WITH_SECRET = 'TWO_FA_ENABLED_WITH_SECRET',
}
